image: node:14.15.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@13.2.1
    - npm install
    - npm run deploy
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
    - main
