image: node:14.15.0
josb test:
  script:
    - node ipconf.js
    - echo "job test ******************** "
job json server:
  script:
    - npm install -g json-server
    - npm run server:json
    - echo "end json server ******************** "
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@13.2.1
    - npm install
    - npm run deploy
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
    - main
